# Generated by Django 5.2.16 on 2026-10-01 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projectarchitecturenode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('AI/ML', 'AI/ML'), ('Generative AI', 'Generative AI'), ('Full Stack', 'Full Stack'), ('QA Automation', 'QA Automation'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=50)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('file', models.FileField(upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='ResumeDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='portfolio.resumeversion')),
            ],
        ),
    ]
