# Generated by Django 5.2.16 on 2026-10-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_resumeversion_resumedownload'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_display', models.CharField(max_length=100)),
                ('date_sort', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('technologies', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='career_timeline/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_sort'],
            },
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='verified_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
