# Generated by Django 5.2.16 on 2026-10-01 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_experience_status_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectarchitecturenode',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectevidence',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectArchitectureConnection',
        ),
        migrations.DeleteModel(
            name='ProjectArchitectureNode',
        ),
        migrations.DeleteModel(
            name='ProjectEvidence',
        ),
    ]
