# Generated by Django 5.2.16 on 2026-10-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_projectarchitecturenode_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('one_page', '1-Page Resume'), ('two_page', '2-Page Resume'), ('cover_letter', 'Cover Letter')], max_length=30, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='resumedownload',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='portfolio.resumedocument'),
        ),
        migrations.DeleteModel(
            name='ResumeVersion',
        ),
    ]
