# Generated by Django 5.2.16 on 2026-10-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_resumedocument_alter_resumedownload_resume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careertimeline',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
