# Generated by Django 5.2.16 on 2026-10-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_careertimeline_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='featured',
        ),
        migrations.AddField(
            model_name='project',
            name='project_category',
            field=models.CharField(choices=[('featured', 'Featured Project'), ('more', 'More Project')], default='more', max_length=20),
        ),
    ]
